import { choices } from './consts.js'

export default async function (self) {
	let variableDefinitions = []
	if (self.config.device === choices.devices[0].id || self.config.device === choices.devices[1].id) {
		//set EM6000 variables
		variableDefinitions.push(
			{ variableId: 'out1_level', name: 'Output 1 Level' },
			{ variableId: 'out2_level', name: 'Output 2 Level' },
			{ variableId: 'rx1_active_bank', name: 'RX1 Active Bank' },
			{ variableId: 'rx2_active_bank', name: 'RX2 Active Bank' },
			{ variableId: 'rx1_active_channel', name: 'RX1 Active Channel' },
			{ variableId: 'rx2_active_channel', name: 'RX2 Active Channel' },
			{ variableId: 'rx1_carrier', name: 'RX1 Carrier' },
			{ variableId: 'rx2_carrier', name: 'RX2 Carrier' },
			{ variableId: 'rx1_name', name: 'RX1 Name' },
			{ variableId: 'rx2_name', name: 'RX2 Name' },
			{ variableId: 'skx1_name', name: 'SKX1 Name' },
			{ variableId: 'skx2_name', name: 'SKX2 Name' },
			{ variableId: 'skx1_lowcut', name: 'SKX1 Lowcut' },
			{ variableId: 'skx2_lowcut', name: 'SKX2 Lowcut' },
			{ variableId: 'skx1_gain', name: 'SKX1 Gain' },
			{ variableId: 'skx2_gain', name: 'SKX2 Gain' },
			{ variableId: 'skx1_capsule', name: 'SKX1 Capsule' },
			{ variableId: 'skx2_capsule', name: 'SKX2 Capsule' },
			{ variableId: 'skx1_battery_percent', name: 'SKX1 Battery Percent' },
			{ variableId: 'skx2_battery_percent', name: 'SKX2 Battery Percent' },
			{ variableId: 'skx1_battery_time', name: 'SKX1 Battery Time' },
			{ variableId: 'skx2_battery_time', name: 'SKX2 Battery Time' },
			{ variableId: 'rx1_rf1', name: 'RX1 RF1' },
			{ variableId: 'rx1_rf2', name: 'RX1 RF2' },
			{ variableId: 'rx1_lqi', name: 'RX1 LQI' },
			{ variableId: 'rx1_af', name: 'RX1 AF' },
			{ variableId: 'rx2_rf1', name: 'RX2 RF1' },
			{ variableId: 'rx2_rf2', name: 'RX2 RF2' },
			{ variableId: 'rx2_lqi', name: 'RX2 LQI' },
			{ variableId: 'rx2_af', name: 'RX2 AF' },
			{ variableId: 'device_version', name: 'Device Version' },
			{ variableId: 'device_name', name: 'Device Name' }
		)
	} else if (self.config.device === choices.devices[2].id) {
		//set L6000 variables
		variableDefinitions.push(
			{ variableId: 'slot1_1_led', name: 'Slot1/1 LED' },
			{ variableId: 'slot1_1_battery_temp', name: 'Slot 1/1 Battery Temp' },
			{ variableId: 'slot1_1_battery_voltage', name: 'Slot 1/1 Battery Voltage' },
			{ variableId: 'slot1_1_battery_capacity', name: 'Slot 1/1 Battery Capcity' },
			{ variableId: 'slot1_1_battery_current', name: 'Slot 1/1 Battery Current' },
			{ variableId: 'slot1_1_battery_energy', name: 'Slot 1/1 Battery Energy' },
			{ variableId: 'slot1_1_battery_operating_time_h', name: 'Slot 1/1 Battery Operating Time Hours' },
			{ variableId: 'slot1_1_battery_operating_time_min', name: 'Slot 1/1 Battery Operating Time Minutes' },
			{ variableId: 'slot1_1_battery_cycle_count', name: 'Slot 1/1 Battery Cycle Count' },
			{ variableId: 'slot1_1_battery_state_of_health', name: 'Slot 1/1 State Of Health' },
			{ variableId: 'slot1_1_battery_time_to_full_h', name: 'Slot 1/1 Time to Full Hours' },
			{ variableId: 'slot1_1_battery_time_to_full_min', name: 'Slot 1/1 Time to Full Minutes' },
			{ variableId: 'slot1_2_led', name: 'Slot 1/2 LED' },
			{ variableId: 'slot1_2_battery_temp', name: 'Slot 1/2 Battery Temp' },
			{ variableId: 'slot1_2_battery_voltage', name: 'Slot 1/2 Battery Voltage' },
			{ variableId: 'slot1_2_battery_capacity', name: 'Slot 1/2 Battery Capcity' },
			{ variableId: 'slot1_2_battery_current', name: 'Slot 1/2 Battery Current' },
			{ variableId: 'slot1_2_battery_energy', name: 'Slot 1/2 Battery Energy' },
			{ variableId: 'slot1_2_battery_operating_time_h', name: 'Slot 1/2 Battery Operating Time Hours' },
			{ variableId: 'slot1_2_battery_operating_time_min', name: 'Slot 1/2 Battery Operating Time Minutes' },
			{ variableId: 'slot1_2_battery_cycle_count', name: 'Slot 1/2 Battery Cycle Count' },
			{ variableId: 'slot1_2_battery_state_of_health', name: 'Slot 1/2 State Of Health' },
			{ variableId: 'slot1_2_battery_time_to_full_h', name: 'Slot 1/2 Time to Full Hours' },
			{ variableId: 'slot1_2_battery_time_to_full_min', name: 'Slot 1/2 Time to Full Minutes' },
			{ variableId: 'slot2_1_led', name: 'Slot 2/1 LED' },
			{ variableId: 'slot2_1_battery_temp', name: 'Slot 2/1 Battery Temp' },
			{ variableId: 'slot2_1_battery_voltage', name: 'Slot 2/1 Battery Voltage' },
			{ variableId: 'slot2_1_battery_capacity', name: 'Slot 2/1 Battery Capcity' },
			{ variableId: 'slot2_1_battery_current', name: 'Slot 2/1 Battery Current' },
			{ variableId: 'slot2_1_battery_energy', name: 'Slot 2/1 Battery Energy' },
			{ variableId: 'slot2_1_battery_operating_time_h', name: 'Slot 2/1 Battery Operating Time Hours' },
			{ variableId: 'slot2_1_battery_operating_time_min', name: 'Slot 2/1 Battery Operating Time Minutes' },
			{ variableId: 'slot2_1_battery_cycle_count', name: 'Slot 2/1 Battery Cycle Count' },
			{ variableId: 'slot2_1_battery_state_of_health', name: 'Slot 2/1 State Of Health' },
			{ variableId: 'slot2_1_battery_time_to_full_h', name: 'Slot 2/1 Time to Full Hours' },
			{ variableId: 'slot2_1_battery_time_to_full_min', name: 'Slot 2/1 Time to Full Minutes' },
			{ variableId: 'slot2_2_led', name: 'Slot 2/2 LED' },
			{ variableId: 'slot2_2_battery_temp', name: 'Slot 2/2 Battery Temp' },
			{ variableId: 'slot2_2_battery_voltage', name: 'Slot 2/2 Battery Voltage' },
			{ variableId: 'slot2_2_battery_capacity', name: 'Slot 2/2 Battery Capcity' },
			{ variableId: 'slot2_2_battery_current', name: 'Slot 2/2 Battery Current' },
			{ variableId: 'slot2_2_battery_energy', name: 'Slot 2/2 Battery Energy' },
			{ variableId: 'slot2_2_battery_operating_time_h', name: 'Slot 2/2 Battery Operating Time Hours' },
			{ variableId: 'slot2_2_battery_operating_time_min', name: 'Slot 2/2 Battery Operating Time Minutes' },
			{ variableId: 'slot2_2_battery_cycle_count', name: 'Slot 2/2 Battery Cycle Count' },
			{ variableId: 'slot2_2_battery_state_of_health', name: 'Slot 2/2 State Of Health' },
			{ variableId: 'slot2_2_battery_time_to_full_h', name: 'Slot 2/2 Time to Full Hours' },
			{ variableId: 'slot2_2_battery_time_to_full_min', name: 'Slot 2/2 Time to Full Minutes' },
			{ variableId: 'slot3_1_led', name: 'Slot 3/1 LED' },
			{ variableId: 'slot3_1_battery_temp', name: 'Slot 3/1 Battery Temp' },
			{ variableId: 'slot3_1_battery_voltage', name: 'Slot 3/1 Battery Voltage' },
			{ variableId: 'slot3_1_battery_capacity', name: 'Slot 3/1 Battery Capcity' },
			{ variableId: 'slot3_1_battery_current', name: 'Slot 3/1 Battery Current' },
			{ variableId: 'slot3_1_battery_energy', name: 'Slot 3/1 Battery Energy' },
			{ variableId: 'slot3_1_battery_operating_time_h', name: 'Slot 3/1 Battery Operating Time Hours' },
			{ variableId: 'slot3_1_battery_operating_time_min', name: 'Slot 3/1 Battery Operating Time Minutes' },
			{ variableId: 'slot3_1_battery_cycle_count', name: 'Slot 3/1 Battery Cycle Count' },
			{ variableId: 'slot3_1_battery_state_of_health', name: 'Slot 3/1 State Of Health' },
			{ variableId: 'slot3_1_battery_time_to_full_h', name: 'Slot 3/1 Time to Full Hours' },
			{ variableId: 'slot3_1_battery_time_to_full_min', name: 'Slot 3/1 Time to Full Minutes' },
			{ variableId: 'slot3_2_led', name: 'Slot 3/2 LED' },
			{ variableId: 'slot3_2_battery_temp', name: 'Slot 3/2 Battery Temp' },
			{ variableId: 'slot3_2_battery_voltage', name: 'Slot 3/2 Battery Voltage' },
			{ variableId: 'slot3_2_battery_capacity', name: 'Slot 3/2 Battery Capcity' },
			{ variableId: 'slot3_2_battery_current', name: 'Slot 3/2 Battery Current' },
			{ variableId: 'slot3_2_battery_energy', name: 'Slot 3/2 Battery Energy' },
			{ variableId: 'slot3_2_battery_operating_time_h', name: 'Slot 3/2 Battery Operating Time Hours' },
			{ variableId: 'slot3_2_battery_operating_time_min', name: 'Slot 3/2 Battery Operating Time Minutes' },
			{ variableId: 'slot3_2_battery_cycle_count', name: 'Slot 3/2 Battery Cycle Count' },
			{ variableId: 'slot3_2_battery_state_of_health', name: 'Slot 3/2 State Of Health' },
			{ variableId: 'slot3_2_battery_time_to_full_h', name: 'Slot 3/2 Time to Full Hours' },
			{ variableId: 'slot3_2_battery_time_to_full_min', name: 'Slot 3/2 Time to Full Minutes' },
			{ variableId: 'slot4_1_led', name: 'Slot 4/1 LED' },
			{ variableId: 'slot4_1_battery_temp', name: 'Slot 4/1 Battery Temp' },
			{ variableId: 'slot4_1_battery_voltage', name: 'Slot 4/1 Battery Voltage' },
			{ variableId: 'slot4_1_battery_capacity', name: 'Slot 4/1 Battery Capcity' },
			{ variableId: 'slot4_1_battery_current', name: 'Slot 4/1 Battery Current' },
			{ variableId: 'slot4_1_battery_energy', name: 'Slot 4/1 Battery Energy' },
			{ variableId: 'slot4_1_battery_operating_time_h', name: 'Slot 4/1 Battery Operating Time Hours' },
			{ variableId: 'slot4_1_battery_operating_time_min', name: 'Slot 4/1 Battery Operating Time Minutes' },
			{ variableId: 'slot4_1_battery_cycle_count', name: 'Slot 4/1 Battery Cycle Count' },
			{ variableId: 'slot4_1_battery_state_of_health', name: 'Slot 4/1 State Of Health' },
			{ variableId: 'slot4_1_battery_time_to_full_h', name: 'Slot 4/1 Time to Full Hours' },
			{ variableId: 'slot4_1_battery_time_to_full_min', name: 'Slot 4/1 Time to Full Minutes' },
			{ variableId: 'slot4_2_led', name: 'Slot 4/2 LED' },
			{ variableId: 'slot4_2_battery_temp', name: 'Slot 4/2 Battery Temp' },
			{ variableId: 'slot4_2_battery_voltage', name: 'Slot 4/2 Battery Voltage' },
			{ variableId: 'slot4_2_battery_capacity', name: 'Slot 4/2 Battery Capcity' },
			{ variableId: 'slot4_2_battery_current', name: 'Slot 4/2 Battery Current' },
			{ variableId: 'slot4_2_battery_energy', name: 'Slot 4/2 Battery Energy' },
			{ variableId: 'slot4_2_battery_operating_time_h', name: 'Slot 4/2 Battery Operating Time Hours' },
			{ variableId: 'slot4_2_battery_operating_time_min', name: 'Slot 4/2 Battery Operating Time Minutes' },
			{ variableId: 'slot4_2_battery_cycle_count', name: 'Slot 4/2 Battery Cycle Count' },
			{ variableId: 'slot4_2_battery_state_of_health', name: 'Slot 4/2 State Of Health' },
			{ variableId: 'slot4_2_battery_time_to_full_h', name: 'Slot 4/2 Time to Full Hours' },
			{ variableId: 'slot4_2_battery_time_to_full_min', name: 'Slot 4/2 Time to Full Minutes' },
			{ variableId: 'device_version', name: 'Device Version' },
			{ variableId: 'device_name', name: 'Device Name' }
		)
	}

	self.setVariableDefinitions(variableDefinitions)
}
